# Generated by Django 3.2.5 on 2022-04-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0005_remove_personalusercard_multi_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
